/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 11 13:28:48 GMT 2026
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WeightHelper_ESTest extends WeightHelper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.getBMICategory(100.0, 30.0);
      assertEquals("Obese", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.getBMICategory(400.0, 400.0);
      assertEquals("Overweight", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.getBMICategory(100.0, 18.5);
      assertEquals("Normal weight", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      double double0 = weightHelper0.calculateBMI(934.9174538770656, 934.9174538770656);
      assertEquals(10.696131469714674, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      double double0 = weightHelper0.calculateBMI(0.0, (-653.622187582));
      assertEquals(Double.NEGATIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      double double0 = weightHelper0.calculateBMI(1.0, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.getBMICategory(0.0, 400.55470320283405);
      assertEquals("Obese", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.getBMICategory(370.04, 0.0);
      assertEquals("Underweight", string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.getBMICategory(0.0, 0.0);
      assertEquals("Obese", string0);
  }
}
